### ISSUE TITLE
Error Loading Extension

### ISSUE THREAD

**Issue by johannes-z** [vuejs/vue-devtools#61]
Just checked out the repo, installed the extension and did as instructed. This is what error message I get in chrome when trying to load shells/chrome. I'm on Windows 10.
Chrome: Version 47.0.2526.80 m

Failed to load extension from: ~\Desktop\vue-devtools\shells\chrome
Could not load background script 'build/background.js'.

**Comment by yyx990803** [comment]
The build script would fail on Windows because I was using unix env var export. It should work now (make sure to do a clean `npm install`)

**Comment by johannes-z** [comment]
I gave this up back then, but now tried it again. On a side note, there are some other changes I had to do:
Firstly I had to run `npm install --dev`, because otherwise eslint and webpack wouldn't be loaded. Then there is the `zip` script, which I changed to `7z.exe a chrome.zip shells/chrome`, but I don't think it's needed anyway.
Lastly, the build script would still fail because of `NODE_ENV`. I just removed `NODE_ENV=production` from the script and now it's working. I'm not entirely sure what this should accomplish in the first place. So the `build` script now looks as follows:
`"build": "npm run lint && cd shells/chrome && webpack --progress --hide-modules && npm run zip"`

**Comment by nisbeti** [comment]
npm-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/0.12.7_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@3.10.8
3 info using node@v6.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle vue-devtools@2.3.1~prebuild: vue-devtools@2.3.1
6 silly lifecycle vue-devtools@2.3.1~prebuild: no script for prebuild, continuing
7 info lifecycle vue-devtools@2.3.1~build: vue-devtools@2.3.1
8 verbose lifecycle vue-devtools@2.3.1~build: unsafe-perm in lifecycle true
9 verbose lifecycle vue-devtools@2.3.1~build: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ian/vue-devtools/node_modules/.bin:/usr/local/Cellar/node/0.12.7_1/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/git/bin:/var/root/bin:/Users/ian/bin:/Users/ian/.composer/vendor/bin:/Users/ian/spark-installer
10 verbose lifecycle vue-devtools@2.3.1~build: CWD: /Users/ian/vue-devtools
11 silly lifecycle vue-devtools@2.3.1~build: Args: [ '-c',
11 silly lifecycle   'npm run lint && cd shells/chrome && cross-env NODE_ENV=production webpack --progress --hide-modules' ]
12 silly lifecycle vue-devtools@2.3.1~build: Returned: code: 1  signal: null
13 info lifecycle vue-devtools@2.3.1~build: Failed to exec build script
14 verbose stack Error: vue-devtools@2.3.1 build: `npm run lint && cd shells/chrome && cross-env NODE_ENV=production webpack --progress --hide-modules`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid vue-devtools@2.3.1
16 verbose cwd /Users/ian/vue-devtools
17 error Darwin 14.5.0
18 error argv "/usr/local/Cellar/node/0.12.7_1/bin/node" "/usr/local/bin/npm" "run" "build"
19 error node v6.6.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error vue-devtools@2.3.1 build: `npm run lint && cd shells/chrome && cross-env NODE_ENV=production webpack --progress --hide-modules`
22 error Exit status 1
23 error Failed at the vue-devtools@2.3.1 build script 'npm run lint && cd shells/chrome && cross-env NODE_ENV=production webpack --progress --hide-modules'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the vue-devtools package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run lint && cd shells/chrome && cross-env NODE_ENV=production webpack --progress --hide-modules
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs vue-devtools
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls vue-devtools
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
