### ISSUE TITLE
vuex.state x vuex.getters

### ISSUE THREAD

**Issue by jbruni** [vuejs/vue-devtools#80]
I'm not sure but it seems vue-devtools is still trying to get "state" from components instead of "getters:

https://github.com/vuejs/vue-devtools/blob/master/src/devtools/components/ComponentInspector.vue#L25

Anyway: I was able to see the computed `state`s in the component inspector before upgrading to Vuex 0.6.1... now I can't see the corresponding `getters`

**EDIT**: already realized that the linked code is not related to the issue; anyway, the issue exists: I could see the computed "getters" (state) in the component inspector, but now I can't see anymore

**Comment by jbruni** [comment]
Furthermore, I am seeing in the console:

> [vuex] vuex.state option will been deprecated in 1.0. Use vuex.getters instead.

But I am not using `state` in my app code anymore... I wonder if this is coming from vue-devtools...?

**Comment by yyx990803** [comment]
The line you found has nothing to do with vuex, but yeah current version of devtools is not identifying vuex getters from plain state properties.

The the warning - not sure, maybe I shipped a build using the locally linked vuex... anyway should be fixed in next release.

**Comment by jbruni** [comment]
The warning was my fault... there was a remaining `vuex.state` in my app which had not been removed. Sorry.

I just updated vue-devtools to check if getters are appearing now... but I got an empty/blank panel, just like other users are reporting. I've upgraded Chrome from v. 48 to 49, but didn't resolve the issue.
